### ISSUE TITLE
Possible BDE Cache Issue?

### ISSUE THREAD

**Issue by forensicmatt** [log2timeline/dfvfs#65] opened 2015-11-23 18:04 UTC
I have noticed when I set the credential for a BDE volume, I cannot set it again. The following test code shows that if you use the correct password first, the incorrect password also appears to work. If you use the incorrect password first, the correct password does not work.

With *PASSWORD_SET = password_set1* both passwords work.
With *PASSWORD_SET = password_set2* both passwords fail.

```
#!/usr/bin/python
# -*- coding: utf-8 -*-
'''Test BDE Cred Issue

Test uses dfvfs test image 'bdetogo.raw'
'''

import os

from dfvfs.lib import definitions as dfvfs_definitions
from dfvfs.analyzer import analyzer as dfvfs_analyzer
from dfvfs.resolver import resolver as dfvfs_resolver
from dfvfs.resolver import context as dfvfs_context
from dfvfs.path import factory as dfvfs_factory
from dfvfs.volume import tsk_volume_system
from dfvfs.vfs import bde_file_system

source_file = 'bdetogo.raw'

#Using this password set both passwords pass#
password_set1 = [u'bde-TEST',u'bad-password']
#Using this password set both passwords fail#
password_set2 = [u'bad-password',u'bde-TEST']

PASSWORD_SET = password_set1

for password in PASSWORD_SET:
    print 'Using password: {}'.format(password)
    
    os_path_spec = dfvfs_factory.Factory.NewPathSpec(
        dfvfs_definitions.TYPE_INDICATOR_OS,
        location=source_file
    )
    
    volume_bde_path_spec = dfvfs_factory.Factory.NewPathSpec(
        dfvfs_definitions.TYPE_INDICATOR_BDE,
        parent=os_path_spec
    )
    
    dfvfs_resolver.Resolver.key_chain.SetCredential(
        volume_bde_path_spec,
        'password',
        password
    )
    
    volume_fs_path_spec = dfvfs_factory.Factory.NewPathSpec(
        dfvfs_definitions.TYPE_INDICATOR_TSK,
        location=u'/',
        parent=volume_bde_path_spec
    )
    
    try:
        file_system = dfvfs_resolver.Resolver.OpenFileSystem(
            volume_fs_path_spec
        )
        print 'password pass: {}'.format(password)
    except Exception as e:
        print 'no go on password: {}. Error: {}'.format(password,str(e))

print 'end'
```

Here is output with *PASSWORD_SET = password_set1* where both passwords work.
```
Using password: bde-TEST
password pass: bde-TEST
Using password: bad-password
password pass: bad-password
end
```
Here is output with *PASSWORD_SET = password_set2* where both passwords fail.
```
Using password: bad-password
no go on password: bad-password. Error: 'pybde_volume_seek_offset: unable to seek offset. libbde_internal_volume_seek_offset: invalid volume - volume is locked.'
FS_Info_Con: (tsk3.c:207) Unable to open the image as a filesystem: Cannot determine file system type
Using password: bde-TEST
no go on password: bde-TEST. Error: 'pybde_volume_seek_offset: unable to seek offset. libbde_internal_volume_seek_offset: invalid volume - volume is locked.'
FS_Info_Con: (tsk3.c:207) Unable to open the image as a filesystem: Cannot determine file system type
end
```

Any ideas?

**Comment by joachimmetz** [comment] 2015-11-23 22:15
Thx, I'll have a look as soon time permits

**Comment by joachimmetz** [comment] 2015-11-25 03:02
The key chain is defined as a class member in:
https://github.com/log2timeline/dfvfs/blob/master/dfvfs/resolver/resolver.py#L17

That could be the cause of it. I'll likely change the code to pass the keychain or attach it to the resolver instead.

**Comment by joachimmetz** [comment] 2015-11-25 04:17
There are 2 issues here:

* file_system should be closed after usage otherwise it will remain cached in the resolver; this is something you'll have to change in your code. Just add: `file_system.Close()` when you're done.
* when OpenFileSystem fails the BDE volume is not cleaned up; this is something that needs to be changed in dfvfs

I'm also wondering if the [source scanner](https://github.com/log2timeline/dfvfs/blob/master/dfvfs/helpers/source_scanner.py) might be a better approach you're trying different password against a BDE volume. Technically TSK could fail to open the file system while the BDE volume was successfully unlocked.

**Comment by joachimmetz** [comment] 2015-11-25 05:08
Try this patch for the second issue: http://codereview.appspot.com/274570043

**Comment by joachimmetz** [comment] 2015-11-25 17:40
Patch has been merged. I'll close the issue, let me know if the fix works for you and reopen the issue if needed.

**Closed by joachimmetz** 2015-11-25 17:40 UTC
Labels: bug

**Comment by forensicmatt** [comment] 2015-11-30 16:30
I added the file_system.Close() and used the new updates. All works as expected now. Source scanner is the better idea. Thank you!
