### ISSUE TITLE
Error in bde_file_io unittests

### ISSUE THREAD

**Issue by dc3-plaso** [log2timeline/dfvfs#145] opened 2016-05-17 14:19 UTC
When running run_tests.py using d88fe0c I get the following errors for bde_file_io tests:

```
ERROR: testOpenCloseInode (file_io.bde_file_io.BDEFileTest)
Test the open and close functionality using an inode.
------------------------------------------------------
Traceback (most recent call last):
  File "C:\dev\dfvfs\tests\file_io\bde_file_io.py", line 34, in testOpenCloseInode
    self._TestOpenClose(self._bde_path_spec)
  File ".\tests\file_io\test_lib.py", line 35, in _TestOpenCloseInode
    file_object.open(path_spec=path_spec)
  File ".\dfvfs\file_io\file_io.py", line73, in open
    self._Open(path_spec=path_spec, mode=mode)
  File ".\dfvfs\file_io\tsk_file_io.py", line 55, in _Open
    path_spec, resolver_context=self._resolver_context)
  File " .\dfvfs\resolver\resolver.py", line 171, in OpenFileSystem
    u'Unable to open file system with error: {0:s}'.format(exception))
BackEndError: Unable to open file system with error: FS_Info_Con: (tsk3.c:207) Unable to open the image as a filesystem: Cannot determine file system type
```

(This is repeated for the testOpenCloseLocation, testRead, testSeek, and testScan.)

I'm running this on 64-bit Windows 7 using Python 2.7 64-bit.

**Comment by joachimmetz** [comment] 2016-05-17 17:13
Thanks for the report, this might be an issue in the build of the pybde. I'll have a look as soon time permits.

**Comment by dc3-plaso** [comment] 2016-05-19 16:01
I just upgraded pybde from 20141023 to the latest 20160418 and I am still having the issue.

**Comment by joachimmetz** [comment] 2021-06-06 15:39
Unclear what the root cause is but test is currently passing on AppVeyor 32-bit and 64-bit e.g. https://ci.appveyor.com/project/log2timeline/dfvfs/build/job/6ach81m90uvt45vl?fullLog=true#L1643

Closing issue

**Closed by joachimmetz** 2021-06-06 15:39 UTC
Labels: deployment
