### ISSUE TITLE
IOError when opening a BDE encrypted volume inside an EWF container

### ISSUE THREAD

**Issue by Mustachu** [log2timeline/dfvfs#392] opened 2019-05-03 13:23 UTC
Hi,

When trying to scan for path specifications inside an EWF container, dfvfs crashes on opening an BDE encrypted volume inside:

```
base_path_spec = scanner.GetBasePathSpecs(options.source)
  File "/usr/local/lib/python2.7/site-packages/dfvfs/helpers/volume_scanner.py", line 427, in GetBasePathSpecs
    self._source_scanner.Scan(scan_context)
  File "/usr/local/lib/python2.7/site-packages/dfvfs/helpers/source_scanner.py", line 662, in Scan
    self._ScanNode(scan_context, scan_node, auto_recurse=auto_recurse)
  File "/usr/local/lib/python2.7/site-packages/dfvfs/helpers/source_scanner.py", line 479, in _ScanNode
    scan_context, scan_node, auto_recurse=auto_recurse)
  File "/usr/local/lib/python2.7/site-packages/dfvfs/helpers/source_scanner.py", line 617, in _ScanVolumeSystemRootNode
    self._ScanNode(scan_context, sub_scan_node, auto_recurse=auto_recurse)
  File "/usr/local/lib/python2.7/site-packages/dfvfs/helpers/source_scanner.py", line 454, in _ScanNode
    self._ScanEncryptedVolumeNode(scan_context, scan_node)
  File "/usr/local/lib/python2.7/site-packages/dfvfs/helpers/source_scanner.py", line 570, in _ScanEncryptedVolumeNode
    scan_node.path_spec, resolver_context=self._resolver_context)
  File "/usr/local/lib/python2.7/site-packages/dfvfs/resolver/resolver.py", line 112, in OpenFileObject
    file_object.open(path_spec=path_spec_object)
  File "/usr/local/lib/python2.7/site-packages/dfvfs/file_io/file_io.py", line 76, in open
    self._Open(path_spec=path_spec, mode=mode)
  File "/usr/local/lib/python2.7/site-packages/dfvfs/file_io/file_object_io.py", line 64, in _Open
    self._file_object = self._OpenFileObject(path_spec)
  File "/usr/local/lib/python2.7/site-packages/dfvfs/file_io/bde_file_io.py", line 40, in _OpenFileObject
    bde_volume, path_spec, file_object, resolver.Resolver.key_chain)
  File "/usr/local/lib/python2.7/site-packages/dfvfs/lib/bde.py", line 28, in BDEVolumeOpen
    bde_volume.open_file_object(file_object)
IOError: pybde_volume_open_file_object: unable to open volume. libbde_metadata_read_block: invalid metadata block signature. libbde_volume_open_read: unable to read primary metadata block. libbde_volume_open_file_io_handle: unable to read from file IO handle.
```

The exact same code works perfectly when handling the raw device exposed by **ewfmount**, suggesting the problem could be on how dfvfs handles the interaction between the EWF container and the BDE volume.
Unfortunately I cannot share the original file.

dfvfs version(from check_dependencies):
```
Checking availability and versions of dependencies.
[OK]		Crypto version: 2.6.1
[OK]		dfdatetime version: 20190116
[OK]		dtfabric version: 20180808
[OPTIONAL]	backports.lzma version: 0.0.13
[OK]		pybde version: 20180806
[OK]		pyewf version: 20171104
[OK]		pyfsntfs version: 20170315
[OK]		pyfvde version: 20180108
[OK]		pyfwnt version: 20180117
[OK]		pyqcow version: 20180831
[OK]		pysigscan version: 20170124
[OK]		pysmdev version: 20171112
[OK]		pysmraw version: 20171105
[OK]		pytsk3 version: 20180225
[OK]		pyvhdi version: 20170223
[OK]		pyvmdk version: 20170226
[OK]		pyvshadow version: 20170902
[OK]		pyvslvm version: 20160110
[OK]		sqlite3 version: 3.22.0
[OK]		yaml version: 3.13
```

**Comment by joachimmetz** [comment] 2019-05-03 13:48
Please try the stable version of libewf/pyewf https://github.com/libyal/libewf-legacy

**Comment by Mustachu** [comment] 2019-05-06 09:04
Hi,
`pyewf version: 20140807` is working as expected, no problem to open the BDE volume insode the EWF container.  
Let me know if you want further testing/debug on my side to resolve the libewf problem.

**Comment by joachimmetz** [comment] 2019-05-06 09:40
Thx 20171104 is known experimental release, which I'll look at when time permits

**Comment by joachimmetz** [comment] 2019-05-06 14:08
Closing issue as duplicate of https://github.com/libyal/libewf/issues/38

**Closed by joachimmetz** 2019-05-06 14:08 UTC
