### ISSUE TITLE
Test failing with custom built libvslvm

### ISSUE THREAD

**Issue by hillu** [log2timeline/dfvfs#108] opened 2016-02-04 18:58 UTC
While trying to update the Debian package, I a number of `libvslvm` / `libbfio` errors. Only pasting the first one here. The `libbfio` version used with `libvslvm` is 20160108-1 (Debian package), all other libraries are built from the local copy.shipped with `libvslvm-experimental-20160110.tar.gz`.

<pre>
Test the ReadSerializedObject and WriteSerializedObject functions. ... ok

======================================================================
ERROR: testOpenClose (file_io.lvm_file_io.LVMFileTest)
Test the open and close functionality.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bengen/p/deb/plaso/dfvfs/tests/file_io/lvm_file_io.py", line 34, in testOpenClose
    file_object.open(path_spec=path_spec)
  File "./dfvfs/file_io/file_io.py", line 73, in open
    self._Open(path_spec=path_spec, mode=mode)
  File "./dfvfs/file_io/lvm_file_io.py", line 58, in _Open
    path_spec, resolver_context=self._resolver_context)
  File "./dfvfs/resolver/resolver.py", line 171, in OpenFileSystem
    u'Unable to open file system with error: {0:s}'.format(exception))
BackEndError: Unable to open file system with error: pyvslvm_handle_open_file_object: unable to
 open handle. libcdata_internal_array_resize: invalid entry free function. libcdata_array_remov
e_entry: unable to resize array. libbfio_pool_remove_handle: unable to remove handle: 0. libvsl
vm_handle_open_read: unable to remove file IO handle: 0 from pool. libvslvm_handle_open_file_io
_handle: unable to read from handle.
</pre>

**Comment by joachimmetz** [comment] 2016-02-05 08:31
Can you attach config.log of your build libvsvlm.

**Comment by hillu** [comment] 2016-02-05 16:06
[config.log.txt](https://github.com/log2timeline/dfvfs/files/119418/config.log.txt)

**Comment by joachimmetz** [comment] 2016-02-06 10:14
```
Building:
   libcstring support:                         local
   libcerror support:                          local
   libcthreads support:                        local
   libcdata support:                           local
   libclocale support:                         local
   libcnotify support:                         local
   libcsplit support:                          local
   libuna support:                             local
   libcfile support:                           local
   libcpath support:                           local
   libbfio support:                            yes
   libfcache support:                          local
   libfdata support:                           local
   libfvalue support:                          local
   libcsystem support:                         local
   FUSE support:                               libfuse

Features:
   Multi-threading support:                    pthread
   Wide character type support:                no
   vslvmtools are build as static executables: no
   Python (pyvslvm) support:                   no
   Python version 2 (pyvslvm) support:         2.7
   Python version 3 (pyvslvm) support:         3.5
   Verbose output:                             no
   Debug output:                               no
```

The problem is you're linking to a version of libbfio that is too old for libvslvm. Try adding --with-libbfio=no to your configure.

**Comment by joachimmetz** [comment] 2016-02-06 10:17
This will eventually be fixed by a new libbfio release, but I really recommend not building against a stand-alone libbfio unless you really need that functionality. Closing issue.

**Closed by joachimmetz** 2016-02-06 10:17 UTC
Labels: question
